# Generated by Django 2.1.15 on 2021-02-02 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='entities',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AddField(
            model_name='tweet',
            name='entities_extracted',
            field=models.BooleanField(default=False),
        ),
    ]
